### ISSUE TITLE
QDepthwiseConv2D can't work

### ISSUE THREAD

**Issue by tu1258** [google/qkeras#43]
The codes to reproduce are at below. They are based on [mnist.py](https://github.com/google/qkeras/blob/master/experimental/cmnist.py) The import path may be different in your case.

### QConv2D
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import DepthwiseConv2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
# from lo import *
import numpy as np
from qkeras.qkeras import *
# from qkeras import print_qstats
# from qkeras import QActivation
# from qkeras import QConv2D
# from qkeras import QDense
# from qkeras import quantized_bits
# from qkeras import ternary


np.random.seed(42)
OPTIMIZER = Adam(lr=0.002)
NB_EPOCH = 10
BATCH_SIZE = 32
VERBOSE = 1
NB_CLASSES = 10
N_HIDDEN = 100
VALIDATION_SPLIT = 0.1
RESHAPED = 784


def QConv2DModel(load_weights=False):
  """Construct QConv2DModel."""

  x = x_in = Input((28,28,1), name="input")
  x = QActivation("quantized_relu(2)", name="act_i")(x)

  x = Conv2D(32, (3, 3), strides=(2, 2), name="conv2d_0_m")(x)
  x = BatchNormalization(name="bn0")(x)
  x = QActivation("quantized_relu(2)", name="act0_m")(x)

  x = Conv2D(64, (3, 3), strides=(2, 2), name="conv2d_1_m")(x)
  x = BatchNormalization(name="bn1")(x)
  x = QActivation("quantized_relu(2)", name="act1_m")(x)

  x = Conv2D(64, (3, 3), strides=(2, 2), name="conv2d_2_m")(x)
  x = BatchNormalization(name="bn2")(x)
  x = QActivation("quantized_relu(2)", name="act2_m")(x)

  x = Flatten(name="flatten")(x)

  x = QDense(
      NB_CLASSES,
      kernel_quantizer=quantized_bits(4, 0, 1),
      bias_quantizer=quantized_bits(4, 0, 1),
      name="dense2")(x)
  x = Activation("softmax", name="softmax")(x)

  model = Model(inputs=[x_in], outputs=[x])
  model.summary()
  model.compile(loss="categorical_crossentropy",
                optimizer=OPTIMIZER, metrics=["accuracy"])


  return model



"""Use DenseModel.
Args:
  weights_f: weight file location.
  load_weights: load weights when it is True.
"""
model = QConv2DModel()
batch_size = BATCH_SIZE
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(60000, 28, 28, 1)
x_test = x_test.reshape(10000, 28, 28, 1)
x_train = x_train.astype("float32")
x_test = x_test.astype("float32")
x_train /= 256.
x_test /= 256.
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")
y_train = to_categorical(y_train, NB_CLASSES)
y_test = to_categorical(y_test, NB_CLASSES)

model.fit(
    x_train,
    y_train,
    batch_size=batch_size,
    epochs=NB_EPOCH,
    verbose=VERBOSE,
    validation_split=VALIDATION_SPLIT)

score = model.evaluate(x_test, y_test, verbose=False)
print("Test score:", score[0])
print("Test accuracy:", score[1])

```

### QDepthwiseConv2D
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import DepthwiseConv2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
# from lo import *
import numpy as np
from qkeras.qkeras import *
# from qkeras import print_qstats
# from qkeras import QActivation
# from qkeras import QConv2D
# from qkeras import QDense
# from qkeras import quantized_bits
# from qkeras import ternary


np.random.seed(42)
OPTIMIZER = Adam(lr=0.002)
NB_EPOCH = 10
BATCH_SIZE = 32
VERBOSE = 1
NB_CLASSES = 10
N_HIDDEN = 100
VALIDATION_SPLIT = 0.1
RESHAPED = 784


def QConv2DModel(load_weights=False):
  """Construct QConv2DModel."""

  x = x_in = Input((28,28,1), name="input")
  x = QActivation("quantized_relu(2)", name="act_i")(x)

  x = QConv2D(32, (3, 3), strides=(1,1), name="conv2d_0_m")(x)
  x = BatchNormalization(name="bn0")(x)
  x = QActivation("quantized_relu(2)", name="act0_m")(x)

  x = QDepthwiseConv2D((3, 3), name="dwconv2d_1_m")(x)
  x = BatchNormalization(name="bn1")(x)
  x = QActivation("quantized_relu(2)", name="act1_m")(x)

  x = QDepthwiseConv2D((3, 3), name="dwconv2d_2_m")(x)
  x = BatchNormalization(name="bn2")(x)
  x = QActivation("quantized_relu(2)", name="act2_m")(x)

  x = Flatten(name="flatten")(x)

  x = QDense(
      NB_CLASSES,
      kernel_quantizer=quantized_bits(4, 0, 1),
      bias_quantizer=quantized_bits(4, 0, 1),
      name="dense2")(x)
  x = Activation("softmax", name="softmax")(x)

  model = Model(inputs=[x_in], outputs=[x])
  model.summary()
  model.compile(loss="categorical_crossentropy",
                optimizer=OPTIMIZER, metrics=["accuracy"])


  return model



"""Use DenseModel.
Args:
  weights_f: weight file location.
  load_weights: load weights when it is True.
"""
model = QConv2DModel()
batch_size = BATCH_SIZE
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(60000, 28, 28, 1)
x_test = x_test.reshape(10000, 28, 28, 1)
x_train = x_train.astype("float32")
x_test = x_test.astype("float32")
x_train /= 256.
x_test /= 256.
print(x_train.shape[0], "train samples")
print(x_test.shape[0], "test samples")
y_train = to_categorical(y_train, NB_CLASSES)
y_test = to_categorical(y_test, NB_CLASSES)

model.fit(
    x_train,
    y_train,
    batch_size=batch_size,
    epochs=NB_EPOCH,
    verbose=VERBOSE,
    validation_split=VALIDATION_SPLIT)

score = model.evaluate(x_test, y_test, verbose=False)
print("Test score:", score[0])
print("Test accuracy:", score[1])

```

The error shown when running **QDepthwiseConv2D**
```
Traceback (most recent call last):
  File "mnist.py", line 123, in <module>
    validation_split=VALIDATION_SPLIT)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/training/r08943133/venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 'pred' passed float expected bool while building NodeDef 'functional_1/dwconv2d_1_m/cond/switch_pred/_2' using Op<name=Switch; signature=data:T, pred:bool -> output_false:T, output_true:T; attr=T:type> [Op:__inference_train_function_2682]

```

**Comment by zhuangh** [comment]
Hi @tu1258 

Please use the latest master branch. We pushed the fix before https://github.com/google/qkeras/commit/ba6c5b97f0896f9b49cce2b4ca7705874b04432d

Let me know if you still have the problem, thank you!

**Comment by tu1258** [comment]
Solved, thanks!
